import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import LandingPage from '../../assets/LandingPage'
import { ButtonView } from './p/dash'
import { useAuthStore } from '@/utils/useAuthStore'
import Link from 'next/link'
import { DASHBOARD } from '@/utils/config'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const {user}=useAuthStore()

  return (
    <>
      <Head>
        <title>Upcycle</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='min-h-screen grid place-items-center'>
        <div className='flex flex-col items-center gap-7'>

          <LandingPage />
          <Link href={!user? '/auth': DASHBOARD}>
            <ButtonView title={user? 'go to Dashboard': 'Get started'} />
          </Link>
        </div>

      </main>
    </>
  )
}
