import Head from "next/head"
import { REGISTER_PROVIDER_API } from '@/utils/config';
import { Field, Form, Formik } from "formik";
import axios from "axios";
import { potential_provider } from "@prisma/client";
import { toast } from "react-toastify";
import { getErrorStringFromAxiosErr } from "../p/add-project";
import { withAuth } from "@/authGuards/withAuth";
import { withNoAuth } from "@/authGuards/withNoAuth";


const PotentialProviderForm = () => {
    return (
        <>
            <Head>
                <title>Upcycle - Register as a provider</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


            <main className="min-h-screen flex flex-col justify-center">
                <div className="min-w-[400px] mx-auto rounded-2xl bg-gradient-to-r from-pink-500 via-red-500 to-yellow-500 p-1 shadow-xl">
                    <div className='flex flex-col items-center rounded-xl bg-white p-4 sm:p-6 lg:p-8'>
                        <img src='/auth-logo.png' className="w-40 mb-5" />

                        <Formik
                            initialValues={{ name: '', email: '', phone: '', address: '', why_join: '', experience: '', }}
                            onSubmit={async (values, { resetForm }) => {
                                const payload: Omit<potential_provider, 'id'> = values
                                try {
                                    const response = await axios.post(REGISTER_PROVIDER_API, payload)
                                    resetForm()
                                    toast.success('Successfully submitted the application form! 🔥')
                                } catch (err: any) {
                                    toast.error(getErrorStringFromAxiosErr(err))
                                }
                            }}
                        >

                            <Form className="space-y-4 w-full">

                                <div className="text-xs text-red-500 px-4">
                                    Please ensure that the EMAIL has either twitter or google social signin enabled!
                                </div>
                                <div className="">
                                    <label className="sr-only" htmlFor="name">Name</label>
                                    {/* <Field type='' */}
                                    <Field required className="w-full rounded-lg border-gray-200 p-3 text-sm border" placeholder="Store Name" type="text" id="name" name='name' />
                                </div>
                                <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                                    <div>
                                        <label className="sr-only" htmlFor="email">Email</label>
                                        <Field required className="w-full rounded-lg border-gray-200 p-3 text-sm border" placeholder="Email address" type="email" id="email" name='email' />
                                    </div>
                                    <div>
                                        <label className="sr-only" htmlFor="phone">Phone</label>
                                        <Field required className="w-full rounded-lg border-gray-200 p-3 text-sm border" placeholder="Phone Number" type="tel" id="phone" name='phone' />
                                    </div>
                                </div>

                                <div>
                                    <label className="sr-only" htmlFor="address">Complete Address of the shop/home</label>
                                    <Field as='textarea' required className="w-full rounded-lg border-gray-200 p-3 text-sm border" rows={3} placeholder="Complete Address of the shop/home" id="address" name='address' />
                                </div>


                                <div>
                                    <label className="sr-only" htmlFor="why_join">Why you want to join our platform?</label>
                                    <Field as='textarea' required className="w-full rounded-lg border-gray-200 p-3 text-sm border" rows={4} placeholder="Why you want to join our platform?" id="why_join" name='why_join' />
                                </div>


                                <div>
                                    <label className="sr-only" htmlFor="experience">Tell us a bit about your experience with modifying clothes</label>
                                    <Field as='textarea' required className="w-full rounded-lg border-gray-200 p-3 text-sm border" rows={4} placeholder="Tell us a bit about your experience with modifying clothes" id="experience" name='experience' />
                                </div>


                                <div className="mt-4">
                                    <button type="submit" className="inline-block w-full rounded-lg bg-black px-5 py-3 font-medium text-white sm:w-auto">
                                        Submit Application
                                    </button>
                                </div>

                            </Form>

                        </Formik>


                    </div>

                </div>

            </main>

        </>
    )
}

export default withNoAuth(PotentialProviderForm)
